# Generated by Django 5.0 on 2024-02-04 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_following_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following_system',
            name='following',
        ),
        migrations.AddField(
            model_name='following_system',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
