# Generated by Django 5.0 on 2024-02-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_liking_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liking_system',
            name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='liking_system',
            name='user',
        ),
        migrations.AddField(
            model_name='liking_system',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='network.post'),
        ),
        migrations.AddField(
            model_name='liking_system',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='users_who_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
