# Generated by Django 5.0 on 2024-02-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_liking_system_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liking_System',
        ),
    ]
