# Generated by Django 5.0 on 2024-02-08 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_delete_liking_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liking_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='network.post')),
                ('users_who_like', models.ManyToManyField(related_name='users_who_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
