# Generated by Django 5.0 on 2024-02-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_liking_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
